/* Permissions file generated by flow2code */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

const permissions = {
	"user.create": "Permission to create / modify user",
	"user.tag": "Permission to modify user's tag",
	"user.perms": "Permission to change user's perms",
	"user.admin": "Permission to do everything on User",
};

export default permissions;
